language: csharp
dist: xenial
mono: none
dotnet: 2.2
os:
  - linux
branches:
  only:
    - master

before_script:
  - dotnet restore

script: 
  - dotnet build
  - dotnet test Blog.Test/Blog.Test.csproj